### ISSUE TITLE
Unit tests passing but `soloist` command fails with latest gems

### ISSUE THREAD

**Issue by aramprice** [pivotal-sprout/sprout-exemplar#9]
`Gemfile.lock` was removed in https://github.com/pivotal-sprout/sprout-exemplar/commit/9ccf4571e565738601298258efcd184e8d5633c3 to allow early warning of gem issues.

See [build #45](https://travis-ci.org/pivotal-sprout/sprout-exemplar/builds/118608024)

```
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/dependency.rb:296:in `to_specs': Could not find 'bundler' (>= 1.10) among 73 total gem(s) (Gem::LoadError)
    from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/specification.rb:1209:in `block in activate_dependencies'
    from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/specification.rb:1198:in `each'
    from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/specification.rb:1198:in `activate_dependencies'
    from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/specification.rb:1180:in `activate'
    from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_gem.rb:48:in `gem'
    from /Users/travis/build/pivotal-sprout/sprout-exemplar/tmp/ruby/2.0.0/bin/chef-solo:22:in `<main>'
```

**Comment by drich10** [comment]
@wendorf - seeing this on the ops manager sprout as well

**Comment by aramprice** [comment]
This is the [`Gemfilie.lock`](https://raw.githubusercontent.com/pivotal-sprout/sprout-exemplar/b77717ac7b968188f462bd00f32bdde1bde685a7/Gemfile.lock) that was working previously

```
GEM
  remote: https://rubygems.org/
  specs:
    ast (2.0.0)
    astrolabe (1.3.0)
      parser (>= 2.2.0.pre.3, < 3.0)
    awesome_print (1.2.0)
    chef (11.16.4)
      chef-zero (~> 2.1, >= 2.1.4)
      diff-lcs (~> 1.2, >= 1.2.4)
      erubis (~> 2.7)
      ffi-yajl (~> 1.0)
      highline (~> 1.6, >= 1.6.9)
      mime-types (~> 1.16)
      mixlib-authentication (~> 1.3)
      mixlib-cli (~> 1.4)
      mixlib-config (~> 2.0)
      mixlib-log (~> 1.3)
      mixlib-shellout (~> 1.4)
      net-ssh (~> 2.6)
      net-ssh-multi (~> 1.1)
      ohai (~> 7.4)
      plist (~> 3.1.0)
      pry (~> 0.9)
      rest-client (>= 1.0.4, <= 1.6.7)
    chef-zero (2.2.1)
      ffi-yajl (~> 1.1)
      hashie (~> 2.0)
      mixlib-log (~> 1.3)
      rack
    chefspec (4.1.1)
      chef (>= 11.14)
      fauxhai (~> 2.0)
      rspec (~> 3.0)
    coderay (1.1.0)
    diff-lcs (1.2.5)
    erubis (2.7.0)
    fauxhai (2.2.0)
      net-ssh
      ohai
    ffi (1.9.6)
    ffi-yajl (1.2.0)
      ffi (~> 1.5)
      libyajl2 (~> 1.0)
    foodcritic (4.0.0)
      erubis
      gherkin (~> 2.11)
      nokogiri (~> 1.5)
      rake
      rufus-lru (~> 1.0)
      treetop (~> 1.4)
      yajl-ruby (~> 1.1)
    gherkin (2.12.2)
      multi_json (~> 1.3)
    hashie (2.1.2)
    highline (1.6.21)
    ipaddress (0.8.0)
    librarian (0.1.2)
      highline
      thor (~> 0.15)
    librarian-chef (0.0.4)
      chef (>= 0.10)
      librarian (~> 0.1.0)
      minitar (>= 0.5.2)
    libyajl2 (1.1.0)
    method_source (0.8.2)
    mime-types (1.25.1)
    mini_portile (0.6.1)
    minitar (0.5.4)
    mixlib-authentication (1.3.0)
      mixlib-log
    mixlib-cli (1.5.0)
    mixlib-config (2.1.0)
    mixlib-log (1.6.0)
    mixlib-shellout (1.6.1)
    multi_json (1.10.1)
    net-ssh (2.9.1)
    net-ssh-gateway (1.2.0)
      net-ssh (>= 2.6.5)
    net-ssh-multi (1.2.0)
      net-ssh (>= 2.6.5)
      net-ssh-gateway (>= 1.2.0)
    nokogiri (1.6.4.1)
      mini_portile (~> 0.6.0)
    ohai (7.4.0)
      ffi (~> 1.9)
      ffi-yajl (~> 1.0)
      ipaddress
      mime-types (~> 1.16)
      mixlib-cli
      mixlib-config (~> 2.0)
      mixlib-log
      mixlib-shellout (~> 1.2)
      systemu (~> 2.6.4)
      wmi-lite (~> 1.0)
    parser (2.2.0.pre.7)
      ast (>= 1.1, < 3.0)
      slop (~> 3.4, >= 3.4.5)
    plist (3.1.0)
    polyglot (0.3.5)
    powerpack (0.0.9)
    pry (0.10.1)
      coderay (~> 1.1.0)
      method_source (~> 0.8.1)
      slop (~> 3.4)
    rack (1.5.2)
    rainbow (2.0.0)
    rake (10.3.2)
    rest-client (1.6.7)
      mime-types (>= 1.16)
    rspec (3.1.0)
      rspec-core (~> 3.1.0)
      rspec-expectations (~> 3.1.0)
      rspec-mocks (~> 3.1.0)
    rspec-core (3.1.7)
      rspec-support (~> 3.1.0)
    rspec-expectations (3.1.2)
      diff-lcs (>= 1.2.0, < 2.0)
      rspec-support (~> 3.1.0)
    rspec-mocks (3.1.3)
      rspec-support (~> 3.1.0)
    rspec-support (3.1.2)
    rubocop (0.27.1)
      astrolabe (~> 1.3)
      parser (>= 2.2.0.pre.7, < 3.0)
      powerpack (~> 0.0.6)
      rainbow (>= 1.99.1, < 3.0)
      ruby-progressbar (~> 1.4)
    ruby-progressbar (1.7.0)
    rufus-lru (1.0.5)
    slop (3.6.0)
    soloist (1.0.3)
      awesome_print
      chef
      hashie (~> 2.0)
      librarian-chef
      net-ssh
      thor
    systemu (2.6.4)
    thor (0.19.1)
    treetop (1.5.3)
      polyglot (~> 0.3)
    wmi-lite (1.0.0)
    yajl-ruby (1.2.1)

PLATFORMS
  ruby

DEPENDENCIES
  chefspec
  foodcritic
  rspec
  rubocop
  soloist

BUNDLED WITH
   1.10.6
```

**Comment by aramprice** [comment]
I've found that when I ran `bundle update` with a local bundle dir configured (ex: [`tmp/`](https://github.com/pivotal-sprout/sprout-exemplar/blob/master/.bundle/config) I've needed to remove the entire `tmp/bundle/` dir before re-bundling with an unmodified `Gemfile.lock` in order for the problem above to be resolved.

**Comment by wendorf** [comment]
I did some testing this weekend, and learned that chef 12.8.x added an explicit dependency on bundler. I added a commit on master that includes a Gemfile with chef 12.7.x and passes (https://travis-ci.org/pivotal-sprout/sprout-exemplar/builds/122161878), and a commit on top of that that updates to chef 12.8.x and fails (https://travis-ci.org/pivotal-sprout/sprout-exemplar/builds/122162452).

The PR that changed this is likely https://github.com/chef/chef/pull/4478.

I haven't yet looked into how to resolve the issue, but this should be enough information to go off of.

**Comment by aramprice** [comment]
excellent detective work @wendorf, thank you.

**Comment by wendorf** [comment]
@aramprice I found that if I remove the `.bundle` directory, this problem goes away. See [this Travis build](https://travis-ci.org/pivotal-sprout/sprout-exemplar/builds/128740829) (there are some extra commits on that branch that were needed to get things green, but the main thing was removing `.bundle`). I noticed you also added this directory to a few other cookbooks. What is the benefit of adding the directory?

Is there a way to get soloist to execute correctly without removing `.bundle`? If not, how would you feel about removing it across all of our cookbooks?

**Comment by aramprice** [comment]
@wendorf one of the issues I found with not having the `.bundle/confg` with:

```yaml
---
BUNDLE_PATH: tmp
BUNDLE_DISABLE_SHARED_GEMS: true
```

is that on OS X 10.11 El Capitan gems fail to install into `/usr/bin` because of the System Integrity Protection (SIP). This isn't alway present on machines which have been upgraded in-place from 10.10 but with it is the default with a fresh install.

Having bundler install to a local dir (`tmp` in the case above) resolves this problem... but apparently at the cost of another.

SIP is already causing some issues with bundler installation because `/usr/bin` is off limits. A workaournd is to specify an [alternate location using `-n /usr/local/bin`](https://github.com/pivotal-sprout/sprout-ruby/issues/1#issuecomment-177320410).

**Comment by aramprice** [comment]
Going to archive this repo, closing.
